apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wwf-app-hpa
  namespace: wwf
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wwf-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: wwf-app-monitor
  namespace: wwf
  labels:
    app: wwf-app
spec:
  selector:
    matchLabels:
      app: wwf-app
  endpoints:
  - port: http
    path: /wwf/actuator/prometheus
    interval: 30s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wwf-network-policy
  namespace: wwf
spec:
  podSelector:
    matchLabels:
      app: wwf-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: wwf
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: kafka
    ports:
    - protocol: TCP
      port: 9092
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53